
export const venues = [
  {
    id: 'venue-05',
    name: 'Nizami Palace',
    location: 'Hyderabad (West)',
    hallType: 'Banquet Hall',
    images: [
      'https://picsum.photos/seed/v5a/800/450',
      'https://picsum.photos/seed/v5b/800/450',
      'https://picsum.photos/seed/v5c/800/450',
    ],
    baseCost: 220000,
    bookedDates: ['2024-08-30'],
    supportedEvents: ['Marriages (Weddings)', 'Sangeeths', 'Corporate Events', 'General Parties/Gatherings'],
  },
  {
    id: 'venue-10',
    name: 'Hi-Tech Convention',
    location: 'Hyderabad (Central)',
    hallType: 'Auditorium',
    images: [
      'https://picsum.photos/seed/v10a/800/450',
      'https://picsum.photos/seed/v10b/800/450',
      'https://picsum.photos/seed/v10c/800/450',
    ],
    baseCost: 110000,
    bookedDates: ['2024-09-25', '2024-09-26'],
    supportedEvents: ['Corporate Events', 'Conferences', 'Birthday Parties'],
  },
  {
    id: 'venue-15',
    name: 'Charminar Courtyard',
    location: 'Hyderabad (South)',
    hallType: 'Open Space',
    images: [
      'https://picsum.photos/seed/v15a/800/450',
      'https://picsum.photos/seed/v15b/800/450',
      'https://picsum.photos/seed/v15c/800/450',
    ],
    baseCost: 240000,
    bookedDates: ['2024-08-29', '2024-09-29'],
    supportedEvents: ['Marriages (Weddings)', 'Sangeeths', 'General Parties/Gatherings', 'Night Parties'],
  },
  {
    id: 'venue-16',
    name: 'Golkonda Fort Lawns',
    location: 'Hyderabad (West)',
    hallType: 'Party Lawn',
    images: [
      'https://picsum.photos/seed/v16a/800/450',
      'https://picsum.photos/seed/v16b/800/450',
    ],
    baseCost: 180000,
    bookedDates: ['2024-09-02', '2024-09-03'],
    supportedEvents: ['Birthday Parties', 'General Parties/Gatherings', 'Sangeeths'],
  },
  {
    id: 'venue-17',
    name: 'Secunderabad Club',
    location: 'Hyderabad (North)',
    hallType: 'Banquet Hall',
    images: [
      'https://picsum.photos/seed/v17a/800/450',
      'https://picsum.photos/seed/v17b/800/450',
      'https://picsum.photos/seed/v17c/800/450',
    ],
    baseCost: 210000,
    bookedDates: ['2024-09-08'],
    supportedEvents: ['Marriages (Weddings)', 'Corporate Events', 'General Parties/Gatherings'],
  },
  {
    id: 'venue-18',
    name: 'Necklace Road Gardens',
    location: 'Hyderabad (Central)',
    hallType: 'Open Space',
    images: [
      'https://picsum.photos/seed/v18a/800/450',
      'https://picsum.photos/seed/v18b/800/450',
    ],
    baseCost: 150000,
    bookedDates: ['2024-08-28', '2024-09-18'],
    supportedEvents: ['Birthday Parties', 'General Parties/Gatherings', 'Night Parties'],
  },
  {
    id: 'venue-19',
    name: 'Ramoji Film City Events',
    location: 'Hyderabad (East)',
    hallType: 'Auditorium',
    images: [
      'https://picsum.photos/seed/v19a/800/450',
      'https://picsum.photos/seed/v19b/800/450',
      'https://picsum.photos/seed/v19c/800/450',
    ],
    baseCost: 290000,
    bookedDates: ['2024-09-20', '2024-09-21'],
    supportedEvents: ['Corporate Events', 'Marriages (Weddings)', 'Sangeeths'],
  },
  {
    id: 'venue-20',
    name: 'Begumpet Airport Lawns',
    location: 'Hyderabad (North)',
    hallType: 'Party Lawn',
    images: [
      'https://picsum.photos/seed/v20a/800/450',
      'https://picsum.photos/seed/v20b/800/450',
      'https://picsum.photos/seed/v20c/800/450',
    ],
    baseCost: 110000,
    bookedDates: ['2024-09-25', '2024-09-26'],
    supportedEvents: ['Birthday Parties', 'Night Parties', 'General Parties/Gatherings'],
  },
  {
    id: 'venue-21',
    name: 'LB Nagar Banquet',
    location: 'Hyderabad (East)',
    hallType: 'Banquet Hall',
    images: [
      'https://picsum.photos/seed/v21a/800/450',
      'https://picsum.photos/seed/v21b/800/450',
    ],
    baseCost: 95000,
    bookedDates: ['2024-09-15', '2024-09-16'],
    supportedEvents: ['Birthday Parties', 'General Parties/Gatherings', 'Corporate Events'],
  },
];
